import '../utils/clothing_item.dart';

class ClothingItemsData {
  static List<ClothingItem> maleClothingItems = [
    ClothingItem(
      image: 'assets/images/male/frock_coat.png',
      name: 'Frock Coat',
      price: 50.00,
      rating: 4.5,
      brandId: 5,
      categoryId: 8,
      genderId: 1,
      productBrandModel: 'Gucci Coat',
      model3D: 'assets/ar-clothes/3d-objects/male/frock_coat.glb',
    ),
    ClothingItem(
      image: 'assets/images/male/grey_suede_jacket.png',
      name: 'grey suede jacket',
      price: 50.00,
      rating: 4.5,
      brandId: 10,
      categoryId: 8,
      genderId: 1,
      productBrandModel: 'Lacoste Jacket',
      model3D: 'assets/ar-clothes/3d-objects/male/grey_suede_jacket.glb',
    ),
    ClothingItem(
      image: 'assets/images/male/shirt.png',
      name: 'shirt',
      price: 50.00,
      rating: 4.5,
      brandId: 10,
      categoryId: 5,
      genderId: 1,
      productBrandModel: 'Quicksilver Shirt',
      model3D: 'assets/ar-clothes/3d-objects/male/shirt.glb',
    ),
    ClothingItem(
      image: 'assets/images/male/skinny_jeans.png',
      name: 'skinny jeans',
      price: 50.00,
      rating: 4.5,
      brandId: 8,
      categoryId: 4,
      genderId: 1,
      productBrandModel: 'Renzo Acosta Jeans',
      model3D: 'assets/ar-clothes/3d-objects/male/skinny_jeans.glb',
    ),
    ClothingItem(
      image: 'assets/images/male/shirt.png',
      name: 't-shirt',
      price: 50.00,
      rating: 4.5,
      brandId: 2,
      categoryId: 1,
      genderId: 1,
      productBrandModel: 'Nike T-Shirt',
      model3D: 'assets/ar-clothes/3d-objects/male/t-shirt.glb',
    ),
    ClothingItem(
      image: 'assets/images/male/t-shirt_green.png',
      name: 't-shirt green',
      price: 50.00,
      rating: 4.5,
      brandId: 1,
      categoryId: 1,
      genderId: 1,
      productBrandModel: 'Adidas T-Shirt',
      model3D: 'assets/ar-clothes/3d-objects/male/t-shirt_green.glb',
    ),
  ];

  static List<ClothingItem> femaleClothingItems = [
    ClothingItem(
      image: 'assets/images/female/dress.png',
      name: 'Dress',
      price: 50.00,
      rating: 4.5,
      brandId: 6,
      categoryId: 3,
      genderId: 2,
      productBrandModel: 'Zara Dress',
      model3D: 'assets/ar-clothes/3d-objects/female/dress.glb',
    ),
    ClothingItem(
      image: 'assets/images/female/female_short_jeans.png',
      name: 'Short Jeans',
      price: 50.00,
      rating: 4.5,
      brandId: 6,
      categoryId: 4,
      genderId: 2,
      productBrandModel: 'H&M Short Jeans',
      model3D: 'assets/ar-clothes/3d-objects/female/female_short_jeans.glb',
    ),
    ClothingItem(
      image: 'assets/images/female/jacket.png',
      name: 'Jacket',
      price: 50.00,
      rating: 4.5,
      brandId: 5,
      categoryId: 8,
      genderId: 2,
      productBrandModel: 'Gucci Jacket',
      model3D: 'assets/ar-clothes/3d-objects/female/jacket.glb',
    ),
    ClothingItem(
      image: 'assets/images/female/leather_jacket.png',
      name: 'Leather Jacket',
      price: 50.00,
      rating: 4.5,
      brandId: 6,
      categoryId: 8,
      genderId: 2,
      productBrandModel: 'Forever 21 Leather Jacket',
      model3D: 'assets/ar-clothes/3d-objects/female/leather_jacket.glb',
    ),
    ClothingItem(
      image: 'assets/images/female/sweatpants.png',
      name: 'Sweatpants',
      price: 50.00,
      rating: 4.5,
      brandId: 5,
      categoryId: 2,
      genderId: 2,
      productBrandModel: 'Gucci Sweatpants',
      model3D: 'assets/ar-clothes/3d-objects/female/sweatpants.glb',
    ),
    ClothingItem(
      image: 'assets/images/female/women_long_sleeve.png',
      name: 'Sleeve',
      price: 50.00,
      rating: 4.5,
      brandId: 9,
      categoryId: 1,
      genderId: 2,
      productBrandModel: 'Mango Sleeve',
      model3D: 'assets/ar-clothes/3d-objects/female/women_long_sleeve.glb',
    ),
  ];
}
